<script src="{{ asset('asset/libs/jquery/dist/jquery.min.js') }}"></script>
<script src=" {{ asset('asset/libs/bootstrap/dist/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ asset('asset/js/sidebarmenu.js') }}"></script>
<script src="{{ asset('asset/js/app.min.js') }}"></script>
<script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap5.min.js"></script>
<script src="{{ asset('asset/libs/apexcharts/dist/apexcharts.min.js') }}"></script>
<script src="{{ asset('asset/libs/simplebar/dist/simplebar.js') }}"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="{{ asset('asset/js/dashboard.js') }}"></script>
